// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtJWUOpqYFiNXlGrBPjWZhDZeT_6CEQIc',
    appId: '1:640365904139:web:92f5c255ea0199ada4620e',
    messagingSenderId: '640365904139',
    projectId: 'karnataka-ot-registration',
    authDomain: 'karnataka-ot-registration.firebaseapp.com',
    storageBucket: 'karnataka-ot-registration.appspot.com',
    measurementId: 'G-CJ6G1T0VB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8PtgHclkXtKjU3Yh_JU_PTvx7xJvx9ek',
    appId: '1:640365904139:android:a4925a08a7a07ddca4620e',
    messagingSenderId: '640365904139',
    projectId: 'karnataka-ot-registration',
    storageBucket: 'karnataka-ot-registration.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUYhoNZIVICsbX6JUkA5V1tyYQ58nZDLU',
    appId: '1:640365904139:ios:8e708cd530ff05c1a4620e',
    messagingSenderId: '640365904139',
    projectId: 'karnataka-ot-registration',
    storageBucket: 'karnataka-ot-registration.appspot.com',
    androidClientId: '640365904139-1i3u24694ar8tjcusegrksf0c4jm02tr.apps.googleusercontent.com',
    iosClientId: '640365904139-6dervdm8iqlilevl16ia3evmsj7sv79p.apps.googleusercontent.com',
    iosBundleId: 'com.example.otRegistration',
  );
}
